# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'ACFianlAssessment' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON'

  # Pods for ACFianlAssessment

  target 'ACFianlAssessmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ACFianlAssessmentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
